### ISSUE TITLE
Icon Request: Shopping Cart

### ISSUE THREAD

**Issue by alexdaniels11** [colebemis/feather#159] opened 2017-07-24 11:59 UTC
If you'd like to request an icon, please provide the following information:
> - shopping, cart, or shopping cart
> - shopping cart button on an app or website
> - here's amazon's walmart's and barnes & noble's

![screen shot 2017-07-24 at 7 58 31 am](https://user-images.githubusercontent.com/8548846/28522454-148a01fc-7046-11e7-91e8-2170a66687a1.png)
![screen shot 2017-07-24 at 7 58 47 am](https://user-images.githubusercontent.com/8548846/28522453-14880a00-7046-11e7-88d1-ae9ff27f128a.png)
![screen shot 2017-07-24 at 7 59 04 am](https://user-images.githubusercontent.com/8548846/28522455-148c4584-7046-11e7-8c06-22ff4a304a2a.png)

**Comment by Swizz** [comment] 2017-07-24 12:07
Duplicate of #20 #79 ~#144~ ~#155~

@colebemis It seem like this one is heavily needed

**Comment by colebemis** [comment] 2017-07-24 16:54
I guess this just moved to the top of my list :)

**Comment by alexdaniels11** [comment] 2017-07-24 16:58
Nice, thanks man. We really do appreciate the work you're doing here, @colebemis.

**Closed** 2017-07-30 07:33 UTC
Labels: icon-request
